webtalk_init -webtalk_dir C:/Users/Li Bozhao/source/repos/EE2026_FinalProject2020S1/SoundDisplay.sim/sim_1/behav/xsim/xsim.dir/simClk_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Mar 22 04:32:03 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7cddb133-d803-4f4e-ae23-12a8fc33b973" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0917254c695c4cb5998f17b74e73445e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "73" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2208 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "9" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "187 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "17 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "239" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "53" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "60508_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2775164253 -regid "" -xml C:/Users/Li Bozhao/source/repos/EE2026_FinalProject2020S1/SoundDisplay.sim/sim_1/behav/xsim/xsim.dir/simClk_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Li Bozhao/source/repos/EE2026_FinalProject2020S1/SoundDisplay.sim/sim_1/behav/xsim/xsim.dir/simClk_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Li Bozhao/source/repos/EE2026_FinalProject2020S1/SoundDisplay.sim/sim_1/behav/xsim/xsim.dir/simClk_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
